###Â Load csv with function read_csv

In [16]:
import pandas as pd
import os

In [2]:
df = pd.read_csv("../datasets/titanic/titanic3.csv")

In [9]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [14]:
len(df.columns)

14

In [15]:
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [13]:
df.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881135,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413500,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.166700,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

In [17]:
df2 = pd.read_csv("../datasets/customer-churn-model/Customer Churn Model.txt")

In [19]:
df2.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [22]:
df2.columns.values

array(['State', 'Account Length', 'Area Code', 'Phone', "Int'l Plan",
       'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls',
       'Day Charge', 'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins',
       'Night Calls', 'Night Charge', 'Intl Mins', 'Intl Calls',
       'Intl Charge', 'CustServ Calls', 'Churn?'], dtype=object)

In [24]:
df2_col = pd.read_csv("../datasets/customer-churn-model/Customer Churn Columns.csv")
print(df2_col, type(df2_col))
df2_col_list = df2_col["Column_Names"].tolist()
print(df2_col_list, type(df2_col_list))df

   Column_Names
0             A
1             B
2             C
3             D
4             E
5             F
6             G
7             H
8             I
9             J
10            K
11            L
12            M
13            N
14            O
15            P
16            Q
17            R
18            S
19            T
20            U <class 'pandas.core.frame.DataFrame'>
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U'] <class 'list'>

In [31]:
df2 = pd.read_csv("../datasets/customer-churn-model/Customer Churn Model.txt", header=None, 
                  names= df2_col_list)

In [32]:
df2.head()

,A,B,C,D,E,F,G,H,I,J,...,L,M,N,O,P,Q,R,S,T,U
0,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
1,KS,128,415,382-4657,no,yes,25,265.100000,110,45.070000,...,99,16.780000,244.700000,91,11.010000,10.000000,3,2.700000,1,False.
2,OH,107,415,371-7191,no,yes,26,161.600000,123,27.470000,...,103,16.620000,254.400000,103,11.450000,13.700000,3,3.700000,1,False.
3,NJ,137,415,358-1921,no,no,0,243.400000,114,41.380000,...,110,10.300000,162.600000,104,7.320000,12.200000,5,3.290000,0,False.
4,OH,84,408,375-9999,yes,no,0,299.400000,71,50.900000,...,88,5.260000,196.900000,89,8.860000,6.600000,7,1.780000,2,False.

In [27]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
       'O', 'P', 'Q', 'R', 'S', 'T', 'U'],
      dtype='object')

## Load the data with the funtion open

In [40]:
#first parameter is the path from where you are going to read the data
#secon parameter 'r' is to read only , 'rw' is to read and write and 'w' is to write
#we can use the 'a' if we want to write include more information in the file 
df3 = open("../datasets/customer-churn-model/Customer Churn Model.txt", "r" )

In [41]:
cols = df3.readline().strip().split(",")
print(cols)
n_cols = len(cols)

['State', 'Account Length', 'Area Code', 'Phone', "Int'l Plan", 'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls', 'Day Charge', 'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins', 'Night Calls', 'Night Charge', 'Intl Mins', 'Intl Calls', 'Intl Charge', 'CustServ Calls', 'Churn?']

In [42]:
n_cols

21

In [44]:
count = 0
main_dict = {}
for col in cols:
    main_dict[col] = []

In [47]:
for line in df3:
    values = line.strip().split(',')
    for i in range(len(cols)):
        main_dict[cols[i]].append(values[i])
    count += 1

print(f'Total of number of rows is {count}, number of columns {n_cols} ')

Total of number of rows is 3333, number of columns 21

In [49]:
df3 = pd.DataFrame(main_dict)
df3.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.100000,110,45.070000,...,99,16.780000,244.700000,91,11.010000,10.000000,3,2.700000,1,False.
1,OH,107,415,371-7191,no,yes,26,161.600000,123,27.470000,...,103,16.620000,254.400000,103,11.450000,13.700000,3,3.700000,1,False.
2,NJ,137,415,358-1921,no,no,0,243.400000,114,41.380000,...,110,10.300000,162.600000,104,7.320000,12.200000,5,3.290000,0,False.
3,OH,84,408,375-9999,yes,no,0,299.400000,71,50.900000,...,88,5.260000,196.900000,89,8.860000,6.600000,7,1.780000,2,False.
4,OK,75,415,330-6626,yes,no,0,166.700000,113,28.340000,...,122,12.610000,186.900000,121,8.410000,10.100000,3,2.730000,3,False.

### Read and Write a File with Python

In [51]:
intFile = "../datasets/customer-churn-model/Customer Churn Model.txt"
outFile = "../datasets/customer-churn-model/Tab2 Customer Churn Model.txt"

In [57]:
with open(intFile, "r") as intFile1:
    with open(outFile, "w") as outFile1:
        for line in intFile1:
            fields = line.strip().split(',') 
            outFile1.write("\t".join(fields))
            outFile1.write("\n")

In [59]:
df4 = pd.read_csv(outFile, sep='\t')
df4.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

### Read Data from a URL

In [67]:
url = 'http://winterolympicsmedals.com/medals.csv'

In [71]:
df5 = pd.read_csv(url)

In [73]:
import csv
import urllib3

In [76]:
http = urllib3.PoolManager()
r = http.request('GET', url)
r.status
response = r.data

In [77]:
cr = csv.reader(response)

In [79]:
response

b'<!doctype html><html lang="en"><head> <title data-react-helmet="true">data.world</title>    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="origin-when-cross-origin"><meta name="og:image" content="https://d2ogkq1rg66kh0.cloudfront.net/site-resources/images/fb-image-share.3a87a6eb.png"><meta name="og:site_name" content="data.world"><meta name="twitter:card" content="summary"><meta name="twitter:site" content="@datadotworld"><meta property="fb:app_id" content="776416075825233"><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inconsolata|Lato:300,300i,400,400i,700,700i"><link rel="search" href="/opensearch.xml" type="application/opensearchdescription+xml" title="data.world">  <link rel="apple-touch-icon" sizes="57x57" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/apple-touch-icon-57x57.png"><link rel="apple-touch-icon" sizes="60x60" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/apple-touch-icon-60x60.png"><link rel="apple-touch-icon" sizes="72x72" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/apple-touch-icon-72x72.png"><link rel="apple-touch-icon" sizes="76x76" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/apple-touch-icon-76x76.png"><link rel="apple-touch-icon" sizes="114x114" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/apple-touch-icon-114x114.png"><link rel="apple-touch-icon" sizes="120x120" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/apple-touch-icon-120x120.png"><link rel="apple-touch-icon" sizes="144x144" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/apple-touch-icon-144x144.png"><link rel="apple-touch-icon" sizes="152x152" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/apple-touch-icon-152x152.png"><link rel="apple-touch-icon" sizes="180x180" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/apple-touch-icon-180x180.png"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="apple-mobile-web-app-title" content="data.world"><meta name="mobile-web-app-capable" content="yes"><meta name="theme-color" content="#fff"><meta name="application-name" content="data.world"><link rel="icon" type="image/png" sizes="32x32" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/favicon-16x16.png"><link rel="shortcut icon" href="https://assets.data.world/icons-d1940ad25da01d05b8f27389101617c1/favicon.ico"><link href="https://assets.data.world/css/vendors~app.29499250c693141d34da.css" rel="stylesheet"><link href="https://assets.data.world/css/vendors~vendors.6c1ca31eec2def9a24e3.css" rel="stylesheet"><link href="https://assets.data.world/css/vendors.fbd98fa7aa5d2bcccde7.css" rel="stylesheet"><link href="https://assets.data.world/css/app.b961641db5e6906ee5b9.css" rel="stylesheet"></head><body ><div id="root"><div class="page-container CoreLayout__embed___1fxWq"><div class="view-container"><div class="LoadingAnimation__loaderOverlay___2zSul LoadingAnimation__default___KhFF6" data-dw="LoadingAnimation"><div class="LoadingAnimation__loaderContainer___2arLY"><div class="LoadingAnimation__spinner___2qQFp">Loading...</div></div></div></div><button data-dw="CoreLayout-HelpDeskButton" type="button" class="CoreLayout__buttonFeedback___2YfGv hidden-xs btn btn-primary">?<span class="text-hide"><span>Feedback</span></span></button></div></div><script type="application/json" id="init-data">{"clients":{},"currentUser":{"authorizedAccounts":null,"requests":[],"unDismissedTourCount":2,"needsAnalyticsAlias":false,"notifications":[],"dismissed":[],"profile":{"abTests":{"buckets":{"landingPageVideo":{"name":"video","value":1},"newCommunityPricingPageAnon":{"name":"new pricing page","value":1},"openAccessTwo":{"name":"normal","value":0},"postgres":{"name":"enabled","value":1},"redshiftRO":{"name":"disabled","value":1},"showNewFeedbackAnon":{"name":"new","value":1},"sidedoorVideo":{"name":"signup","value":0},"sqlAlgebra":{"name":"preferLegacy","value":2},"sqlQuery":{"name":"presto","value":4},"unifiedSearchAnon":{"name":"new","value":1}}},"accountStanding":"good","activeSubscriptionid":"","agentid":"","allowedRoles":[],"avatarUrl":"","bio":"","catalogStatistics":{"analysesCount":0,"datasetsCount":0,"dataTypesCount":0,"glossaryCount":0,"projectsCount":0,"tablesCount":0},"displayName":"","email":"","created":"","company":"","emailVerified":true,"level":"READ","location":"","numFollowers":0,"numFollowing":0,"numOrganizations":0,"orgMode":false,"orgDetails":null,"orgPreferences":null,"relationship":{"member":false,"followed":false},"staticGrants":{"analysisHubEnabled":false,"businessGlossaryEnabled":false,"lineageEnabled":false,"metadataCatalogEnabled":false,"preventGuestAuthorizations":false,"preventGuestUserInvite":false,"preventOpenDatasets":false,"preventSignedShareUrls":false,"samlAllowed":false},"tags":[],"updated":"","userCapabilities":{},"visibility":"","visitorid":"109156be-c4fb-41ea-b1b4-efe1671c580e","website":""},"requestsFetching":false,"authorizedClients":[],"isLoggedIn":false,"onboardThisSession":false,"token":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwcm9kLXVzZXItY2xpZW50IiwiaXNzIjoiYXV0aG9yaXR5OmRhdGFkb3R3b3JsZDo6MEJGMEVCRDMtMkRFNy00OUZCLUI4N0ItQUQwMzA1N0JCODlFIiwiaWF0IjoxNjM1NjkyNDA3LCJyb2xlIjpbXSwiZXhwIjoxNjM1Nzc4ODA3LCJ2aXNpdG9yaWQiOiIxMDkxNTZiZS1jNGZiLTQxZWEtYjFiNC1lZmUxNjcxYzU4MGUiLCJnZW5lcmFsLXB1cnBvc2UiOnRydWUsImF1dGhvcml0eWlkcyI6WyJkYXRhZG90d29ybGQiXX0.HajO2xb_nFPejoPutgAHOKTUYTXXSl9DofyJ-sBcEBGXjJz0h518lGxnMBbxaBu9qlnNrH3FzBdBSiH9kP1JMQ"},"dataset":{"hasError":false,"loadedDatasets":{},"usersDatasets":{},"loadedCurrentUsersDatasets":false,"usersDatasetsTotalCount":0,"customDataTypes":{},"workspacePreferences":{}},"discussion":{},"events":{"status":"closed"},"integration":{"activeIntegrations":[],"userJdbcSources":[],"supportedJdbcSources":[]},"invite":{},"linkedOnboardModal":{"show":false},"loginModal":{"show":false},"queries":{},"requestInfo":{"pathsMarkedAs404":[],"metadata":{}},"requests":{"hasError":false,"loadedResources":{}},"routing":{"locationBeforeTransitions":null},"signUpModal":{"show":false,"treatment":null,"treatmentProps":null},"siteStatus":{"uploadsOperational":true,"queryOperational":true,"websiteOperational":true,"downloadsOperational":true,"shouldAskReload":false,"shouldForceReload":false,"connectionError":false,"incidentName":"","incidentMessage":"","pageStatus":"none"},"treatments":{"isSite":false,"activeTreatments":["showVersions","showWorkspaceTabs","showEntityLinkOptions","showConversionPages","showSignup","showSocialLogin"]},"user":{"hasError":false,"loadedUsers":{},"userFollows":{},"userLikes":{},"userRecentComments":{},"groupAuthorizations":{}}}</script><script type="application/json" id="init-config">{"adwords_pixel_id":"869213640","analytics":{"segment_id":"IXhtZmPohuGM60VHk59cdSbWqWQBB7aR"},"analytics_log_to_console":false,"contact_admin_form_config":[{"type":"input","label":"Email","lookupProperty":"email","readOnly":true,"required":true},{"type":"textarea","label":"Message","placeholder":"Add a message (i.e details that need to be reviewed)","required":true}],"csrf_cookie_name":"_csrf","csrf_header_name":"x-csrf-token","data_provider_agents":["johnsnowlabs","associatedpress"],"dw_tableau_wdc_host_domain":"https:\\u002F\\u002Ftableau.data.world","deployed_environment_full":"prod","facebook_pixel_id":"261984994177057","fb_app_id":"776416075825233","google_chooser_app_id":"956984791354","help_cards":[{"id":"getting_started","header":"Get Started","body":"New to data.world? Start here to find introductory articles.","link":"https:\\u002F\\u002Fdocs.data.world\\u002Fen\\u002F59261-60585-0--Overview-of-data-world.html","imageSrc":"getting-started-lightglow"},{"id":"join_discussion","header":"Join the discussion","body":"Join the general discussion or start your own topic","link":"","imageSrc":"discussions-lightglow"},{"id":"see_documentation","header":"Visit the Help Center","body":"Find general platform documentation and technical tutorials.","link":"https:\\u002F\\u002Fdocs.data.world\\u002F","imageSrc":"documentation-lightglow"},{"id":"contact_support","header":"Contact support","body":"Report an issue or make a suggestion.","link":"https:\\u002F\\u002Fhelp.data.world\\u002Fhc\\u002Fen-us\\u002Frequests\\u002Fnew","imageSrc":"support-lightglow_sales-guy"}],"iframely_key":"e4239223dd4ad21531b3a044840d5898","is_monitored_env":true,"is_vpc":false,"max_upload_size":524288000,"media_upload_domain":"mediauploads.data.world","media_url":"https:\\u002F\\u002Fmedia.data.world","oauth_providers":[{"name":"facebook","display_name":"Facebook","active":true},{"name":"github","display_name":"GitHub","active":true},{"name":"google","display_name":"Google","active":true},{"name":"linkedin","display_name":"LinkedIn","active":false},{"name":"twitter","display_name":"Twitter","active":true}],"openAccessRoutePrefixes":["\\u002Fplaindealerprojects","\\u002Fd1gi\\u002Fmissing-fb-posts-w-share-stats","\\u002Ftravelwarnings\\u002Ftravel-danger","\\u002Ffootprint\\u002Fnfa-2018-edition","\\u002Fpolymathic\\u002Fcasualties-of-the-syrian-civil-war","\\u002Faurielle\\u002Ffortune-500-2017","\\u002Fnjdotcom","\\u002Fian\\u002Fusa-baby-names-national-and-state-by-state","\\u002Fowentemple\\u002Ftext-and-content-features-of-most-persuasive-ted-talks","\\u002Fschnee\\u002Ftangled","\\u002Fchhs\\u002Ffc544658-35c5-4be0-af20-fc703bc57c13","\\u002Fnz-stats-nz\\u002F4e5ebed0-4279-4292-a85f-33c9f2a93f8d","\\u002Fshad\\u002Fcovid-19-time-series-data","\\u002Fmarkmarkoh\\u002Fcoronavirus-data","\\u002Fdallemang\\u002Fcovid-19-data","\\u002Fpolicinginamerica","\\u002Findustryresearch\\u002Fdata-engineer-survey-2021","\\u002Fembed\\u002Fswwo","swwo"],"preferred_oauth_provider":"google","prod_env":true,"profile_interests":["education","finance","government","business","transportation","health","agriculture","environment","sports","entertainment","technology","science","culture","politics","crime"],"request_dataset_access_form_config":[{"type":"input","label":"Full name","lookupProperty":"displayName","required":true,"readOnly":true},{"type":"email","label":"Contact email","placeholder":"Provide an email in the case a dataset administrator needs to reach out","showOptionalFlag":true},{"type":"textarea","label":"Message","placeholder":"Share what you would like to do with this dataset","required":true}],"requests":{"contributionSuggestionInfoText":"You are suggesting changes to this \\u003C%= resourceType %\\u003E that will need to be approved by an admin of this organization. Only you and admins will be able to see your changes until they\xe2\x80\x99re approved.","pendingApprovalsText":"There \\u003C%= pendingApprovalsNumber %\\u003E from the community pending admin approval.","pendingSuggestionsText":"Your suggested changes are visible on the Suggestions tab, but only you and this organization\xe2\x80\x99s admins can see them until they have been approved. The Overview tab displays only approved information.","personalResourceSharedWithText":"This draft \\u003C%= resourceType %\\u003E is within your private collection and only visible to you. It is neither discoverable nor viewable by the data.world community. To open it up to others to view, publish it to an organization.","transferOwnershipMessage":"By publishing this \\u003C%= resourceType %\\u003E to an organization, you are transferring ownership to the organization. Once your draft is published, you will no longer be able to directly edit this \\u003C%= resourceType %\\u003E unless you become a content creator of that organization.","transferOwnershipModalWarningBanner":"Once the organization has published your draft, you will no longer be able to directly edit this \\u003C%= resourceType %\\u003E unless you become a content creator of that organization."},"sentry_dsn_client":"https:\\u002F\\u002Ff763f0cf14f04c75b4789a118ab1beb3@sentry.io\\u002F1486857","server_origin":"https:\\u002F\\u002Fdata.world","sparql_host":"https:\\u002F\\u002Fpdw-sparqlproxy.prod.data.world","stripe_public_key":"pk_live_CPGU5gVFxlkY6pabDXladsMR","swagger_use_case_label_override_org":["oa-test","engie-impact","e-ddw"],"tableau_api_version":"2.8","ui":{"orgAdmin":{"resourceLinks":[{"key":"getting-started","linkDisplayName":"Getting started guide","url":"https:\\u002F\\u002Fdocs.data.world\\u002Fen\\u002F59261-60585-0--Overview-of-data-world.html","newTab":true,"svgIcon":"meta","verticallyAlignIcon":true},{"key":"documentation","linkDisplayName":"Documentation","url":"https:\\u002F\\u002Fdocs.data.world\\u002F","newTab":true,"svgIcon":"meta","verticallyAlignIcon":true},{"key":"integrations","linkDisplayName":"Integrations","url":"\\u002Fintegrations","newTab":true,"svgIcon":"integration","verticallyAlignIcon":true,"showIfAnyDismissed":["onboard-checklist","onboard-checklist-admin"]},{"key":"new-features","linkDisplayName":"New features","url":"https:\\u002F\\u002Fwhatsnew.data.world","newTab":true,"svgIcon":"magic-wand","verticallyAlignIcon":true,"showIfAnyDismissed":["onboard-checklist","onboard-checklist-admin"]}],"welcomeUserCard":{"newUserCard":{"heading":"Welcome to data.world, \\u003C%= displayName %\\u003E!","description":"data.world is where people, data, and analysis come together to make data informed decisions faster.","linkText":"Watch 2 min video","linkBody":"https:\\u002F\\u002Fwww.youtube.com\\u002Fembed\\u002FkdPkWDqks3g?rel=0&amp;showinfo=0&amp;modestbranding=1&amp;controls=0","buttonText":"Take the tour"},"altUserCard":{"heading":"Things look a little different around here.","description":"Welcome to your new home page! Use the Activity menu on the left to easily view and contribute to the latest activity from your own work, your team, or the open data community.","buttonText":"Got it"}},"manageTeamCard":{"heading":"Finish setting up \\u003C%= displayName %\\u003E","buttonText":"Manage your team","buttonLink":"\\u002Factivity\\u002F\\u003C%- agentid %\\u003E"},"connectDataCard":{"heading":"Connect your data sources.","description":"Create datasets for use in multiple projects. Upload data or use connectors to your databases and data platforms.","createButtonText":"Create a dataset","createButtonLink":"\\u002Fcreate-a-dataset?context=\\u003C%- groupid %\\u003E","viewButtonText":"Explore connectors","viewButtonLink":"\\u002Fintegrations"},"onboardChecklist":{"key":"site","items":[{"id":"createAccount","analyticsId":"onboard_checklist.create_account","complete":true,"formattedMessage":{"id":"onboard_checklist.create_account","description":"Text for onboard checklist create account link","defaultMessage":"Create account"}},{"id":"inviteTeam","analyticsId":"onboard_checklist.invite-team","href":"\\u002F\\u003C%- orgAgentid %\\u003E?tab=members","dismissOnClick":"invite-team-link","completeIfDismissed":"invite-team-link","formattedMessage":{"id":"onboard_checklist.invite-team","description":"Text for onboard checklist invite team link","defaultMessage":"Invite your team"}},{"id":"connectData","analyticsId":"onboard_checklist.connect-data","href":"\\u002Fcreate-a-dataset","dismissOnClick":"connect-data-link","completeIfDismissed":"connect-data-link","formattedMessage":{"id":"onboard_checklist.connect-data","description":"Text for onboard checklist connect data link","defaultMessage":"Connect data sources"}},{"id":"exploreIntegrations","analyticsId":"onboard_checklist.explore-integrations","href":"\\u002Fintegrations","target":"_blank","dismissOnClick":"explore-integrations-link","completeIfDismissed":"explore-integrations-link","formattedMessage":{"id":"onboard_checklist.explore-integrations","description":"Text for onboard checklist explore integrations link","defaultMessage":"Explore integrations"}},{"id":"createProject","analyticsId":"onboard_checklist.create-project","href":"\\u002Fcreate-a-project","dismissOnClick":"create-project-link","completeIfDismissed":"create-project-link","formattedMessage":{"id":"onboard_checklist.create-project","description":"Text for onboard checklist create project link","defaultMessage":"Create your first project"}}]},"onboardTour":[{"show":true,"header":"Welcome to data.world!","subhead":"The place for modern data teamwork.","leftCol":"Organize data work so you and your team find what you \\u003Cspan class=\'text-nowrap\'\\u003Eneed faster.\\u003C\\u002Fspan\\u003E","middleCol":"Explore and create a shared understanding of \\u003Cspan class=\'text-nowrap\'\\u003Eyour data.\\u003C\\u002Fspan\\u003E","rightCol":"Share insights and invite more people to participate in \\u003Cspan class=\'text-nowrap\'\\u003Edata teamwork.\\u003C\\u002Fspan\\u003E"},{"show":true,"imageHeaderKey":"search","imageKey":"collaborate","imageAlt":"Start with Data","header":"Start with \\u003Cspan class=\'text-nowrap\'\\u003Efantastic data\\u003C\\u002Fspan\\u003E","subhead":"\\u003Cul class=\'lead\'\\u003E\\n      \\u003Cli\\u003EBrowse thousands of free, open data resources; bookmark your favorites \\u003Cspan class=\'text-nowrap\'\\u003Efor later.\\u003C\\u002Fspan\\u003E\\u003C\\u002Fli\\u003E\\n      \\u003Cli\\u003EGather your own data from almost anywhere into a single \\u003Cspan class=\'text-nowrap\'\\u003Esearchable library.\\u003C\\u002Fspan\\u003E\\u003C\\u002Fli\\u003E\\n      \\u003Cli\\u003EMake it open, share with your team, or keep \\u003Cspan class=\'text-nowrap\'\\u003Eit private.\\u003C\\u002Fspan\\u003E\\u003C\\u002Fli\\u003E\\u003C\\u002Ful\\u003E"},{"show":true,"imageHeaderKey":"bulb","imageKey":"dataProject","imageAlt":"Data Projects","header":"Organize your \\u003Cspan class=\'text-nowrap\'\\u003Edata projects\\u003C\\u002Fspan\\u003E","subhead":"\\u003Cul class=\'lead\'\\u003E\\n      \\u003Cli\\u003ECreate projects that hold everything you need to answer \\u003Cspan class=\'text-nowrap\'\\u003Ecritical questions.\\u003C\\u002Fspan\\u003E\\u003C\\u002Fli\\u003E\\n      \\u003Cli\\u003EAdd context to make it easier for others to discover, understand, and contribute to \\u003Cspan class=\'text-nowrap\'\\u003Eyour projects.\\u003C\\u002Fspan\\u003E\\u003C\\u002Fli\\u003E\\n      \\u003Cli\\u003EImmediately query data without leaving \\u003Cspan class=\'text-nowrap\'\\u003Eyour projects.\\u003C\\u002Fspan\\u003E\\u003C\\u002Fli\\u003E\\u003C\\u002Ful\\u003E"},{"show":true,"imageHeaderKey":"code","imageKey":"slideIntegrations","imageAlt":"Integrations","reverse":true,"header":"Connect the data tools \\u003Cspan class=\'text-nowrap\'\\u003Eyou love\\u003C\\u002Fspan\\u003E","subhead":"\\u003Cul class=\'lead\'\\u003E\\n      \\u003Cli\\u003EAutomatically keep data.world synced with your \\u003Cspan class=\'text-nowrap\'\\u003Edata sources.\\u003C\\u002Fspan\\u003E\\u003C\\u002Fli\\u003E\\n      \\u003Cli\\u003EIntegrate your team\'s favorite tools, from analysis \\u003Cspan class=\'text-nowrap\'\\u003Eto visualization.\\u003C\\u002Fspan\\u003E\\u003C\\u002Fli\\u003E\\u003C\\u002Ful\\u003E"},{"show":true,"imageHeaderKey":"discussions","imageKey":"discussionsCollaboration","imageAlt":"Contributors","header":"Add more brainpower \\u003Cspan class=\'text-nowrap\'\\u003Eto your projects\\u003C\\u002Fspan\\u003E","subhead":"\\u003Cul class=\'lead\'\\u003E\\n      \\u003Cli\\u003EInvite your team to securely and effectively \\u003Cspan class=\'text-nowrap\'\\u003Ework together.\\u003C\\u002Fspan\\u003E\\u003C\\u002Fli\\u003E\\n      \\u003Cli\\u003EManage fine-grained permissions for \\u003Cspan class=\'text-nowrap\'\\u003Eeach member.\\u003C\\u002Fspan\\u003E\\u003C\\u002Fli\\u003E\\n      \\u003Cli\\u003EAsk questions, add insights, bookmark top contributions, \\u003Cspan class=\'text-nowrap\'\\u003Eand more.\\u003C\\u002Fspan\\u003E

### Read XLS and XLSX files

In [82]:
titanic2 = pd.read_excel("../datasets/titanic/titanic3.xls", "titanic3")
titanic2.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [83]:
titanic3 = pd.read_excel("../datasets/titanic/titanic3.xlsx", "titanic3" )
titanic3.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

## Create from a Data Frame a new CSV or Excel file

In [84]:
titanic3.to_csv("../datasets/titanic/titanic_custom_2.csv")

In [85]:
titanic3.to_excel("../datasets/titanic/titanic_custom_2.xls")